# Generated by Django 5.1.7 on 2025-09-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacion',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='tipo',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('bot', 'Bot')], max_length=10),
        ),
    ]
