# Generated by Django 5.1.7 on 2025-04-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('correo_usuario', models.EmailField(max_length=254, unique=True)),
                ('telefono_usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('password_usuario', models.CharField(max_length=255)),
                ('autenticacion_usuario', models.CharField(choices=[('local', 'Local'), ('google', 'Google')], default='local', max_length=10)),
                ('tipo_usuario', models.CharField(choices=[('persona', 'Persona'), ('empresa', 'Empresa')], default='persona', max_length=10)),
                ('fecha_registro_usuario', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
