# Generated by Django 5.1.7 on 2025-04-29 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_usuario_estado_usuario_fecha_nacimiento_usuario_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('descripcion_empresa', models.TextField(blank=True, null=True)),
                ('logo_empresa', models.ImageField(blank=True, null=True, upload_to='logos_empresas/')),
                ('pais_empresa', models.CharField(max_length=100)),
                ('estado_empresa', models.CharField(max_length=100)),
                ('tipo_empresa', models.CharField(choices=[('pequeña', 'Pequeña'), ('mediana', 'Mediana'), ('grande', 'Grande')], max_length=10)),
                ('direccion_empresa', models.CharField(max_length=255)),
                ('latitud_empresa', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_empresa', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('id_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='ecommerce_app.usuario')),
            ],
        ),
    ]
