# Generated by Django 5.1.7 on 2025-05-01 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=100)),
                ('direccion_sucursal', models.TextField()),
                ('telefono_sucursal', models.CharField(max_length=20)),
                ('estado_sucursal', models.CharField(max_length=50)),
                ('latitud_sucursal', models.FloatField()),
                ('longitud_sucursal', models.FloatField()),
                ('id_empresa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='ecommerce_app.empresa')),
            ],
        ),
    ]
