# Generated by Django 5.1.7 on 2025-05-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_producto',
            fields=[
                ('id_categoria_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria_prod', models.CharField(max_length=100)),
                ('descripcion_categoria_prod', models.TextField(blank=True, null=True)),
                ('estatus_categoria_prod', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('fecha_creacion_prod', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
