# Generated by Django 5.1.7 on 2025-05-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_categoria_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_servicio',
            fields=[
                ('id_categoria_serv', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria_serv', models.CharField(max_length=100, unique=True)),
                ('descripcion_categoria_serv', models.TextField(blank=True, null=True)),
                ('estatus_categoria_serv', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('fecha_creacion_categ_serv', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
