# Generated by Django 5.1.7 on 2025-05-22 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_categoria_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=150)),
                ('descripcion_producto', models.TextField(blank=True, null=True)),
                ('marca_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_producto', models.ImageField(blank=True, null=True, upload_to='imagenes_productos/')),
                ('caracteristicas_generales', models.TextField(blank=True, null=True)),
                ('estatus_producto', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('fecha_creacion_producto', models.DateTimeField(auto_now_add=True)),
                ('id_categoria_prod_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='ecommerce_app.categoria_producto')),
                ('id_empresa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='ecommerce_app.empresa')),
            ],
        ),
    ]
