# Generated by Django 5.1.7 on 2025-05-23 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=150)),
                ('descripcion_servicio', models.TextField(blank=True, null=True)),
                ('imagen_servicio', models.ImageField(blank=True, null=True, upload_to='imagenes_servicios/')),
                ('estatus_servicio', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('fecha_creacion_servicio', models.DateTimeField(auto_now_add=True)),
                ('id_categoria_servicios_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='ecommerce_app.categoria_servicio')),
                ('id_empresa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='ecommerce_app.empresa')),
            ],
        ),
    ]
