# Generated by Django 5.1.7 on 2025-06-01 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto_sucursal',
            fields=[
                ('id_producto_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('stock_producto_sucursal', models.PositiveIntegerField(default=0)),
                ('precio_producto_sucursal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_producto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales_producto', to='ecommerce_app.producto')),
                ('id_sucursal_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_sucursal', to='ecommerce_app.sucursal')),
            ],
        ),
    ]
