# Generated by Django 5.1.7 on 2025-08-10 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_producto_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicio_sucursal',
            fields=[
                ('id_servicio_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('precio_servicio_sucursal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilidad_servicio_sucursal', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('id_servicio_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales_servicio', to='ecommerce_app.servicio')),
                ('id_sucursal_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_sucursal', to='ecommerce_app.sucursal')),
            ],
        ),
    ]
