# Generated by Django 5.1.7 on 2025-08-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0010_servicio_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_sucursal',
            name='precio_servicio_sucursal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
