# Generated by Django 5.1.7 on 2025-08-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0011_alter_servicio_sucursal_precio_servicio_sucursal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio_sucursal',
            old_name='disponibilidad_servicio_sucursal',
            new_name='estatus_servicio_sucursal',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='estatus_producto',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='estatus_servicio',
        ),
        migrations.AddField(
            model_name='producto_sucursal',
            name='estatus_producto_sucursal',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
    ]
