# Generated by Django 5.1.7 on 2025-08-11 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0012_mover_estatus_a_producto_servicio_sucursal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio_sucursal',
            old_name='estatus_servicio_sucursal',
            new_name='disponibilidad_servicio_sucursal',
        ),
        migrations.RemoveField(
            model_name='producto_sucursal',
            name='estatus_producto_sucursal',
        ),
    ]
