# Generated by Django 5.1.7 on 2025-08-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0013_rename_estatus_servicio_sucursal_servicio_sucursal_disponibilidad_servicio_sucursal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio_sucursal',
            old_name='disponibilidad_servicio_sucursal',
            new_name='estatus_servicio_sucursal',
        ),
        migrations.AddField(
            model_name='producto_sucursal',
            name='estatus_producto_sucursal',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
    ]
