# Generated by Django 5.1.7 on 2025-08-11 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0014_rename_disponibilidad_servicio_sucursal_servicio_sucursal_estatus_servicio_sucursal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_producto',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='imagen_servicio',
        ),
        migrations.CreateModel(
            name='imagen_producto',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_imagen', models.ImageField(upload_to='imagenes_productos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_producto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ecommerce_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='imagen_servicio',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_imagen', models.ImageField(upload_to='imagenes_servicios/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_servicio_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ecommerce_app.servicio')),
            ],
        ),
    ]
