# Generated by Django 5.1.7 on 2025-08-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0015_remove_producto_imagen_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_sucursal',
            name='condicion_producto_sucursal',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], default='Nuevo', max_length=10),
        ),
    ]
