# Generated by Django 5.1.7 on 2025-08-12 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0016_producto_sucursal_condicion_producto_sucursal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_usuario',
            new_name='rol_usuario',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='id_usuario_fk',
        ),
        migrations.AddField(
            model_name='empresa',
            name='correo_empresa',
            field=models.EmailField(default='temp@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_registro_empresa',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empresa',
            name='password_empresa',
            field=models.CharField(default='temp_password', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rol_empresa',
            field=models.CharField(choices=[('persona', 'Persona'), ('empresa', 'Empresa')], default='empresa', max_length=10),
        ),
    ]
