# Generated by Django 5.1.7 on 2025-08-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0017_rename_tipo_usuario_usuario_rol_usuario_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categoria_producto',
            new_name='categoria_producto_empresa',
        ),
        migrations.RenameModel(
            old_name='categoria_servicio',
            new_name='categoria_servicio_empresa',
        ),
        migrations.RenameField(
            model_name='categoria_producto_empresa',
            old_name='descripcion_categoria_prod',
            new_name='descripcion_categoria_prod_empresa',
        ),
        migrations.RenameField(
            model_name='categoria_producto_empresa',
            old_name='estatus_categoria_prod',
            new_name='estatus_categoria_prod_empresa',
        ),
        migrations.RenameField(
            model_name='categoria_producto_empresa',
            old_name='fecha_creacion_prod',
            new_name='fecha_creacion_prod_empresa',
        ),
        migrations.RenameField(
            model_name='categoria_producto_empresa',
            old_name='id_categoria_prod',
            new_name='id_categoria_prod_empresa',
        ),
        migrations.RenameField(
            model_name='categoria_producto_empresa',
            old_name='nombre_categoria_prod',
            new_name='nombre_categoria_prod_empresa',
        ),
        migrations.RenameField(
            model_name='categoria_servicio_empresa',
            old_name='descripcion_categoria_serv',
            new_name='descripcion_categoria_serv_empresa',
        ),
        migrations.RenameField(
            model_name='categoria_servicio_empresa',
            old_name='estatus_categoria_serv',
            new_name='estatus_categoria_serv_empresa',
        ),
        migrations.RenameField(
            model_name='categoria_servicio_empresa',
            old_name='fecha_creacion_categ_serv',
            new_name='fecha_creacion_categ_serv_empresa',
        ),
        migrations.RenameField(
            model_name='categoria_servicio_empresa',
            old_name='id_categoria_serv',
            new_name='id_categoria_serv_empresa',
        ),
        migrations.RenameField(
            model_name='categoria_servicio_empresa',
            old_name='nombre_categoria_serv',
            new_name='nombre_categoria_serv_empresa',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='correo_empresa',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fecha_registro_empresa',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='password_empresa',
            field=models.CharField(max_length=255),
        ),
    ]
