# Generated by Django 5.1.7 on 2025-08-12 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0018_rename_categoria_producto_categoria_producto_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_producto_empresa',
            name='id_empresa_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_producto', to='ecommerce_app.empresa'),
        ),
        migrations.AddField(
            model_name='categoria_servicio_empresa',
            name='id_empresa_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_servicio', to='ecommerce_app.empresa'),
        ),
    ]
