# Generated by Django 5.1.7 on 2025-08-12 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0019_categoria_producto_empresa_id_empresa_fk_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='producto',
            new_name='producto_empresa',
        ),
        migrations.RenameModel(
            old_name='servicio',
            new_name='servicio_empresa',
        ),
    ]
