# Generated by Django 5.1.7 on 2025-08-12 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0020_rename_producto_producto_empresa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_empresa',
            old_name='caracteristicas_generales',
            new_name='caracteristicas_generales_empresa',
        ),
        migrations.RenameField(
            model_name='producto_empresa',
            old_name='descripcion_producto',
            new_name='descripcion_producto_empresa',
        ),
        migrations.RenameField(
            model_name='producto_empresa',
            old_name='fecha_creacion_producto',
            new_name='fecha_creacion_producto_empresa',
        ),
        migrations.RenameField(
            model_name='producto_empresa',
            old_name='id_producto',
            new_name='id_producto_empresa',
        ),
        migrations.RenameField(
            model_name='producto_empresa',
            old_name='marca_producto',
            new_name='marca_producto_empresa',
        ),
        migrations.RenameField(
            model_name='producto_empresa',
            old_name='modelo_producto',
            new_name='modelo_producto_empresa',
        ),
        migrations.RenameField(
            model_name='producto_empresa',
            old_name='nombre_producto',
            new_name='nombre_producto_empresa',
        ),
        migrations.RenameField(
            model_name='servicio_empresa',
            old_name='descripcion_servicio',
            new_name='descripcion_servicio_empresa',
        ),
        migrations.RenameField(
            model_name='servicio_empresa',
            old_name='fecha_creacion_servicio',
            new_name='fecha_creacion_servicio_empresa',
        ),
        migrations.RenameField(
            model_name='servicio_empresa',
            old_name='id_servicio',
            new_name='id_servicio_empresa',
        ),
        migrations.RenameField(
            model_name='servicio_empresa',
            old_name='nombre_servicio',
            new_name='nombre_servicio_empresa',
        ),
    ]
