# Generated by Django 5.1.7 on 2025-08-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0021_rename_caracteristicas_generales_producto_empresa_caracteristicas_generales_empresa_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='imagen_producto',
            new_name='imagen_producto_empresa',
        ),
        migrations.RenameModel(
            old_name='imagen_servicio',
            new_name='imagen_servicio_empresa',
        ),
        migrations.RenameField(
            model_name='imagen_producto_empresa',
            old_name='fecha_creacion',
            new_name='fecha_creacion_producto_empresa',
        ),
        migrations.RenameField(
            model_name='imagen_producto_empresa',
            old_name='id_imagen',
            new_name='id_imagen_producto_empresa',
        ),
        migrations.RenameField(
            model_name='imagen_producto_empresa',
            old_name='ruta_imagen',
            new_name='ruta_imagen_producto_empresa',
        ),
        migrations.RenameField(
            model_name='imagen_servicio_empresa',
            old_name='fecha_creacion',
            new_name='fecha_creacion_servicio_empresa',
        ),
        migrations.RenameField(
            model_name='imagen_servicio_empresa',
            old_name='id_imagen',
            new_name='id_imagen_servicio_empresa',
        ),
        migrations.RenameField(
            model_name='imagen_servicio_empresa',
            old_name='ruta_imagen',
            new_name='ruta_imagen_servicio_empresa',
        ),
    ]
