# Generated by Django 5.1.7 on 2025-08-13 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0022_rename_imagen_producto_imagen_producto_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_producto_usuario',
            fields=[
                ('id_categoria_prod_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria_prod_usuario', models.CharField(max_length=100)),
                ('descripcion_categoria_prod_usuario', models.TextField(blank=True, null=True)),
                ('estatus_categoria_prod_usuario', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('fecha_creacion_prod_usuario', models.DateTimeField(auto_now_add=True)),
                ('id_usuario_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_producto', to='ecommerce_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='categoria_servicio_usuario',
            fields=[
                ('id_categoria_serv_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria_serv_usuario', models.CharField(max_length=100, unique=True)),
                ('descripcion_categoria_serv_usuario', models.TextField(blank=True, null=True)),
                ('estatus_categoria_serv_usuario', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('fecha_creacion_categ_serv_usuario', models.DateField(auto_now_add=True)),
                ('id_usuario_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_servicio', to='ecommerce_app.usuario')),
            ],
        ),
    ]
