# Generated by Django 5.1.7 on 2025-08-13 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0023_categoria_producto_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto_usuario',
            fields=[
                ('id_producto_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto_usuario', models.CharField(max_length=150)),
                ('descripcion_producto_usuario', models.TextField(blank=True, null=True)),
                ('marca_producto_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo_producto_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('caracteristicas_generales_usuario', models.TextField(blank=True, null=True)),
                ('fecha_creacion_producto_usuario', models.DateTimeField(auto_now_add=True)),
                ('id_categoria_prod_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='ecommerce_app.categoria_producto_usuario')),
                ('id_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='ecommerce_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='imagen_producto_usuario',
            fields=[
                ('id_imagen_producto_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_imagen_producto_usuario', models.ImageField(upload_to='imagenes_productos/')),
                ('fecha_creacion_producto_usuario', models.DateTimeField(auto_now_add=True)),
                ('id_producto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ecommerce_app.producto_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='servicio_usuario',
            fields=[
                ('id_servicio_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio_usuario', models.CharField(max_length=150)),
                ('descripcion_servicio_usuario', models.TextField(blank=True, null=True)),
                ('fecha_creacion_servicio_usuario', models.DateTimeField(auto_now_add=True)),
                ('id_categoria_servicios_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='ecommerce_app.categoria_servicio_usuario')),
                ('id_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='ecommerce_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='imagen_servicio_usuario',
            fields=[
                ('id_imagen_servicio_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_imagen_servicio_usuario', models.ImageField(upload_to='imagenes_servicios/')),
                ('fecha_creacion_servicio_usuario', models.DateTimeField(auto_now_add=True)),
                ('id_servicio_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ecommerce_app.servicio_usuario')),
            ],
        ),
    ]
