# Generated by Django 5.1.7 on 2025-08-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0024_producto_usuario_imagen_producto_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_usuario',
            name='precio_producto_usuario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto_usuario',
            name='stock_producto_usuario',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicio_usuario',
            name='estatus_servicio_usuario',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
        migrations.AddField(
            model_name='servicio_usuario',
            name='precio_servicio_usuario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
