# Generated by Django 5.1.7 on 2025-08-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0025_producto_usuario_precio_producto_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_usuario',
            name='condicion_producto_usuario',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], default='Nuevo', max_length=10),
        ),
        migrations.AddField(
            model_name='producto_usuario',
            name='estatus_producto_usuario',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
    ]
