# Generated by Django 5.1.7 on 2025-08-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0026_producto_usuario_condicion_producto_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_usuario',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_usuario/'),
        ),
    ]
