# Generated by Django 5.1.7 on 2025-08-16 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0027_usuario_foto_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito_compra_producto_empresa',
            fields=[
                ('id_carrito_prod_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('estatuscarrito_prod_empresa', models.CharField(choices=[('activo', 'Activo'), ('pendiente', 'Pendiente')], default='activo', max_length=10)),
                ('fecha_creacion_carrito_prod_empresa', models.DateTimeField(auto_now_add=True)),
                ('total_carrito_prod_empresa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('id_empresa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos_compra', to='ecommerce_app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='carrito_compra_producto_usuario',
            fields=[
                ('id_carrito_prod_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('estatuscarrito_prod_usuario', models.CharField(choices=[('activo', 'Activo'), ('pendiente', 'Pendiente')], default='activo', max_length=10)),
                ('fecha_creacion_carrito_prod_usuario', models.DateTimeField(auto_now_add=True)),
                ('total_carrito_prod_usuario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('id_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos_compra', to='ecommerce_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_compra_producto_empresa',
            fields=[
                ('id_deta_carrito_prod_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_deta_carrito_prod_empresa', models.PositiveIntegerField(default=1)),
                ('precio_unit_deta_carrito_prod_empresa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_deta_carrito_prod_empresa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_agregado_deta_carrito_prod_empresa', models.DateTimeField(auto_now_add=True)),
                ('id_fk_carritocompra_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ecommerce_app.carrito_compra_producto_empresa')),
                ('id_fk_producto_sucursal_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_carrito_empresa', to='ecommerce_app.producto_sucursal')),
                ('idproducto_fk_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_carrito_empresa', to='ecommerce_app.producto_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_compra_producto_usuario',
            fields=[
                ('id_deta_carrito_prod_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_deta_carrito_prod_usuario', models.PositiveIntegerField(default=1)),
                ('precio_unit_deta_carrito_prod_usuario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_deta_carrito_prod_usuario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_agregado_deta_carrito_prod_usuario', models.DateTimeField(auto_now_add=True)),
                ('id_fk_carritocompra_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ecommerce_app.carrito_compra_producto_usuario')),
                ('id_fk_producto_sucursal_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_carrito_usuario', to='ecommerce_app.producto_sucursal')),
                ('idproducto_fk_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_carrito', to='ecommerce_app.producto_usuario')),
            ],
        ),
    ]
