# Generated by Django 5.1.7 on 2025-08-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0029_pedido_empresa_detalle_pedido_empresa_pedido_usuario_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "SET FOREIGN_KEY_CHECKS = 0;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS ecommerce_app_detalle_pedido_empresa;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS ecommerce_app_detalle_pedido_usuario;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS ecommerce_app_pedido_empresa;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS ecommerce_app_pedido_usuario;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "SET FOREIGN_KEY_CHECKS = 1;",
            reverse_sql=""
        ),
    ]
