# Generated by Django 5.1.7 on 2025-08-19 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0030_auto_20250818_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_pedido_usuario',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='detalle_pedido_usuario',
            name='producto_empresa',
        ),
        migrations.RemoveField(
            model_name='detalle_pedido_usuario',
            name='producto_usuario',
        ),
        migrations.RemoveField(
            model_name='detalle_pedido_usuario',
            name='servicio_empresa',
        ),
        migrations.RemoveField(
            model_name='detalle_pedido_usuario',
            name='servicio_usuario',
        ),
        migrations.RemoveField(
            model_name='pedido_empresa',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='pedido_usuario',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='pedido_usuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='detalle_pedido_empresa',
        ),
        migrations.DeleteModel(
            name='detalle_pedido_usuario',
        ),
        migrations.DeleteModel(
            name='pedido_empresa',
        ),
        migrations.DeleteModel(
            name='pedido_usuario',
        ),
    ]
