# Generated by Django 5.1.7 on 2025-08-19 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0031_remove_detalle_pedido_usuario_pedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedido_empresa',
            fields=[
                ('id_pedido_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('numero_pedido', models.CharField(max_length=20, unique=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado_pedido', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion_envio', models.TextField()),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('paypal', 'PayPal')], max_length=50)),
                ('comprobante_pago', models.ImageField(blank=True, null=True, upload_to='comprobantes_pago/')),
                ('notas_pedido', models.TextField(blank=True, null=True)),
                ('id_carrito_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='ecommerce_app.carrito_compra_producto_empresa')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_pedido_empresa',
            fields=[
                ('id_detalle_pedido_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_detalle_pedido', models.PositiveIntegerField()),
                ('precio_unitario_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_detalle_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_fk_producto_sucursal_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pedido_empresa', to='ecommerce_app.producto_sucursal')),
                ('idproducto_fk_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pedido_empresa', to='ecommerce_app.producto_usuario')),
                ('id_pedido_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ecommerce_app.pedido_empresa')),
            ],
        ),
        migrations.CreateModel(
            name='pedido_usuario',
            fields=[
                ('id_pedido_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('numero_pedido', models.CharField(max_length=20, unique=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado_pedido', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion_envio', models.TextField()),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('paypal', 'PayPal')], max_length=50)),
                ('comprobante_pago', models.ImageField(blank=True, null=True, upload_to='comprobantes_pago/')),
                ('notas_pedido', models.TextField(blank=True, null=True)),
                ('id_carrito_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='ecommerce_app.carrito_compra_producto_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_pedido_usuario',
            fields=[
                ('id_detalle_pedido_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_detalle_pedido', models.PositiveIntegerField()),
                ('precio_unitario_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_detalle_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_fk_producto_sucursal_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pedido_usuario', to='ecommerce_app.producto_sucursal')),
                ('idproducto_fk_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pedido_usuario', to='ecommerce_app.producto_usuario')),
                ('id_pedido_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ecommerce_app.pedido_usuario')),
            ],
        ),
    ]
