# Generated by Django 5.1.7 on 2025-08-23 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0032_pedido_empresa_detalle_pedido_empresa_pedido_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitud_servicio_empresa',
            fields=[
                ('id_solicitud_servicio_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_requerida', models.DateField()),
                ('direccion', models.TextField()),
                ('descripcion_detallada', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cotizada', 'Cotizada'), ('aceptada', 'Aceptada'), ('pagada', 'Pagada'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_servicio', to='ecommerce_app.empresa')),
                ('id_servicio_sucursal_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_empresa', to='ecommerce_app.servicio_sucursal')),
                ('id_servicio_usuario_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_empresa', to='ecommerce_app.servicio_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='solicitud_servicio_usuario',
            fields=[
                ('id_solicitud_servicio_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_requerida', models.DateField()),
                ('direccion', models.TextField()),
                ('descripcion_detallada', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cotizada', 'Cotizada'), ('aceptada', 'Aceptada'), ('pagada', 'Pagada'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_servicio_sucursal_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_usuario', to='ecommerce_app.servicio_sucursal')),
                ('id_servicio_usuario_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='ecommerce_app.servicio_usuario')),
                ('id_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_servicio', to='ecommerce_app.usuario')),
            ],
        ),
    ]
