# Generated by Django 5.1.7 on 2025-08-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0033_solicitud_servicio_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_compra_producto_empresa',
            name='precio_original_deta_carrito_prod_empresa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detalle_compra_producto_usuario',
            name='precio_original_deta_carrito_prod_usuario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
