# Generated by Django 5.1.7 on 2025-08-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0034_detalle_compra_producto_empresa_precio_original_deta_carrito_prod_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_usuario',
            name='latitud_entrega_producto',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='producto_usuario',
            name='longitud_entrega_producto',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
