# Generated by Django 5.1.7 on 2025-09-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0035_producto_usuario_latitud_entrega_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_empresa',
            name='comentario_rechazo',
            field=models.TextField(blank=True, help_text='Comentario explicando el motivo del rechazo del pedido', null=True),
        ),
        migrations.AddField(
            model_name='pedido_usuario',
            name='comentario_rechazo',
            field=models.TextField(blank=True, help_text='Comentario explicando el motivo del rechazo del pedido', null=True),
        ),
    ]
