# Generated by Django 5.1.7 on 2025-09-02 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0036_pedido_empresa_comentario_rechazo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificacion_empresa',
            fields=[
                ('id_notificacion_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_notificacion', models.CharField(choices=[('venta_pendiente', 'Venta Pendiente'), ('venta_confirmada', 'Venta Confirmada'), ('venta_rechazada', 'Venta Rechazada'), ('nuevo_pedido', 'Nuevo Pedido'), ('solicitud_servicio', 'Nueva Solicitud de Servicio'), ('servicio_pagado', 'Servicio Pagado')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('no_leida', 'No Leída'), ('leida', 'Leída')], default='no_leida', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('id_empresa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='ecommerce_app.empresa')),
                ('id_pedido_empresa_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='ecommerce_app.pedido_empresa')),
                ('id_solicitud_servicio_empresa_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='ecommerce_app.solicitud_servicio_empresa')),
            ],
        ),
        migrations.CreateModel(
            name='notificacion_usuario',
            fields=[
                ('id_notificacion_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_notificacion', models.CharField(choices=[('pedido_confirmado', 'Pedido Confirmado'), ('pedido_rechazado', 'Pedido Rechazado'), ('pedido_enviado', 'Pedido Enviado'), ('pedido_entregado', 'Pedido Entregado'), ('servicio_cotizado', 'Servicio Cotizado'), ('servicio_aceptado', 'Servicio Aceptado'), ('servicio_completado', 'Servicio Completado')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('no_leida', 'No Leída'), ('leida', 'Leída')], default='no_leida', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('id_pedido_usuario_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='ecommerce_app.pedido_usuario')),
                ('id_solicitud_servicio_usuario_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='ecommerce_app.solicitud_servicio_usuario')),
                ('id_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='ecommerce_app.usuario')),
            ],
        ),
    ]
