# Generated by Django 5.1.7 on 2025-09-04 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0037_notificacion_empresa_notificacion_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='favorito_empresa_sucursal',
            fields=[
                ('id_favorito_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('id_empresa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='ecommerce_app.empresa')),
                ('id_producto_usuario_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_empresa', to='ecommerce_app.producto_usuario')),
                ('id_servicio_usuario_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_empresa', to='ecommerce_app.servicio_usuario')),
            ],
            options={
                'verbose_name': 'Favorito de Empresa',
                'verbose_name_plural': 'Favoritos de Empresas',
                'db_table': 'favoritos_empresas',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('id_empresa_fk', 'id_producto_usuario_fk'), ('id_empresa_fk', 'id_servicio_usuario_fk')},
            },
        ),
        migrations.CreateModel(
            name='favorito_usuario',
            fields=[
                ('id_favorito_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('id_producto_sucursal_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_usuario', to='ecommerce_app.producto_sucursal')),
                ('id_producto_usuario_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_usuario', to='ecommerce_app.producto_usuario')),
                ('id_servicio_sucursal_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_usuario', to='ecommerce_app.servicio_sucursal')),
                ('id_servicio_usuario_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_usuario', to='ecommerce_app.servicio_usuario')),
                ('id_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='ecommerce_app.usuario')),
            ],
            options={
                'verbose_name': 'Favorito de Usuario',
                'verbose_name_plural': 'Favoritos de Usuarios',
                'db_table': 'favoritos_usuarios',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('id_usuario_fk', 'id_producto_sucursal_fk'), ('id_usuario_fk', 'id_producto_usuario_fk'), ('id_usuario_fk', 'id_servicio_sucursal_fk'), ('id_usuario_fk', 'id_servicio_usuario_fk')},
            },
        ),
    ]
