# Generated by Django 5.1.7 on 2025-09-08 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0038_favorito_empresa_sucursal_favorito_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoProducto',
            fields=[
                ('id_atributo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo_dato', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('decimal', 'Decimal'), ('fecha', 'Fecha'), ('booleano', 'Booleano'), ('lista', 'Lista de opciones')], max_length=20)),
                ('opciones', models.JSONField(blank=True, help_text='Para tipo lista: ["opcion1", "opcion2"]', null=True)),
                ('obligatorio', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Atributo de Producto',
                'verbose_name_plural': 'Atributos de Productos',
                'db_table': 'atributo_producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaAtributo',
            fields=[
                ('id_categoria_atributo', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización del atributo')),
                ('fecha_asociacion', models.DateTimeField(auto_now_add=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_asociadas', to='ecommerce_app.atributoproducto')),
                ('categoria_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributos_asociados', to='ecommerce_app.categoria_producto_empresa')),
                ('categoria_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributos_asociados', to='ecommerce_app.categoria_producto_usuario')),
            ],
            options={
                'verbose_name': 'Categoría-Atributo',
                'verbose_name_plural': 'Categorías-Atributos',
                'db_table': 'categoria_atributo',
                'ordering': ['orden', 'fecha_asociacion'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('categoria_empresa__isnull', True), ('categoria_usuario__isnull', False)), models.Q(('categoria_empresa__isnull', False), ('categoria_usuario__isnull', True)), _connector='OR'), name='categoria_atributo_exclusiva')],
                'unique_together': {('atributo', 'categoria_empresa'), ('atributo', 'categoria_usuario')},
            },
        ),
        migrations.CreateModel(
            name='ValorAtributoProducto',
            fields=[
                ('id_valor_atributo', models.AutoField(primary_key=True, serialize=False)),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numero', models.IntegerField(blank=True, null=True)),
                ('valor_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_fecha', models.DateField(blank=True, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='ecommerce_app.atributoproducto')),
                ('producto_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valores_atributos', to='ecommerce_app.producto_empresa')),
                ('producto_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valores_atributos', to='ecommerce_app.producto_usuario')),
            ],
            options={
                'verbose_name': 'Valor de Atributo',
                'verbose_name_plural': 'Valores de Atributos',
                'db_table': 'valor_atributo_producto',
                'ordering': ['atributo__nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('producto_empresa__isnull', True), ('producto_usuario__isnull', False)), models.Q(('producto_empresa__isnull', False), ('producto_usuario__isnull', True)), _connector='OR'), name='valor_atributo_producto_exclusivo')],
                'unique_together': {('producto_empresa', 'atributo'), ('producto_usuario', 'atributo')},
            },
        ),
    ]
