# Generated by Django 5.1.7 on 2025-09-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0039_atributoproducto_categoriaatributo_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atributoproducto',
            table=None,
        ),
        migrations.AlterModelTable(
            name='categoriaatributo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='valoratributoproducto',
            table=None,
        ),
    ]
