# Generated by Django 5.1.7 on 2025-09-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0040_alter_atributoproducto_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_empresa',
            name='marca_producto_empresa',
        ),
        migrations.RemoveField(
            model_name='producto_empresa',
            name='modelo_producto_empresa',
        ),
        migrations.RemoveField(
            model_name='producto_usuario',
            name='marca_producto_usuario',
        ),
        migrations.RemoveField(
            model_name='producto_usuario',
            name='modelo_producto_usuario',
        ),
    ]
