# Generated by Django 5.1.7 on 2025-09-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0041_remove_producto_empresa_marca_producto_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar_chatbot',
            field=models.CharField(default='avatars/Cartoon Style Robot.jpg', help_text='Avatar para el chatbot', max_length=255),
        ),
    ]
