# Generated by Django 5.1.7 on 2025-09-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0042_usuario_avatar_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_servicio_empresa',
            name='fecha_requerida',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='solicitud_servicio_usuario',
            name='fecha_requerida',
            field=models.DateTimeField(),
        ),
    ]
