# Generated by Django 5.1.7 on 2025-09-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0043_alter_solicitud_servicio_empresa_fecha_requerida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_servicio_empresa',
            name='archivo_cotizacion',
            field=models.FileField(blank=True, help_text='Archivo de cotización (PDF, DOC, DOCX, JPG, PNG)', null=True, upload_to='cotizaciones/'),
        ),
        migrations.AddField(
            model_name='solicitud_servicio_empresa',
            name='descripcion_cotizacion',
            field=models.TextField(blank=True, help_text='Descripción de la cotización', null=True),
        ),
        migrations.AddField(
            model_name='solicitud_servicio_empresa',
            name='fecha_cotizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se envió la cotización', null=True),
        ),
        migrations.AddField(
            model_name='solicitud_servicio_empresa',
            name='presupuesto_cotizacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto de la cotización', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_servicio_usuario',
            name='archivo_cotizacion',
            field=models.FileField(blank=True, help_text='Archivo de cotización (PDF, DOC, DOCX, JPG, PNG)', null=True, upload_to='cotizaciones/'),
        ),
        migrations.AddField(
            model_name='solicitud_servicio_usuario',
            name='descripcion_cotizacion',
            field=models.TextField(blank=True, help_text='Descripción de la cotización', null=True),
        ),
        migrations.AddField(
            model_name='solicitud_servicio_usuario',
            name='fecha_cotizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se envió la cotización', null=True),
        ),
        migrations.AddField(
            model_name='solicitud_servicio_usuario',
            name='presupuesto_cotizacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto de la cotización', max_digits=10, null=True),
        ),
    ]
