# Generated by Django 5.1.7 on 2025-09-28 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0044_solicitud_servicio_empresa_archivo_cotizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pago_servicio',
            fields=[
                ('id_pago_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('paypal', 'PayPal'), ('pago_movil', 'Pago Móvil'), ('criptomoneda', 'Criptomoneda')], max_length=50)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_cotizado', models.DecimalField(decimal_places=2, help_text='Monto original de la cotización', max_digits=10)),
                ('comprobante_pago', models.ImageField(blank=True, null=True, upload_to='comprobantes_pago/')),
                ('referencia_pago', models.CharField(blank=True, help_text='Número de referencia del pago', max_length=100, null=True)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, help_text='Fecha límite para confirmar el pago', null=True)),
                ('notas_pago', models.TextField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solicitud_servicio_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ecommerce_app.solicitud_servicio_empresa')),
                ('solicitud_servicio_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ecommerce_app.solicitud_servicio_usuario')),
            ],
            options={
                'verbose_name': 'Pago de Servicio',
                'verbose_name_plural': 'Pagos de Servicios',
                'ordering': ['-fecha_pago'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('solicitud_servicio_empresa__isnull', True), ('solicitud_servicio_usuario__isnull', False)), models.Q(('solicitud_servicio_empresa__isnull', False), ('solicitud_servicio_usuario__isnull', True)), _connector='OR'), name='pago_servicio_solicitud_exclusiva')],
            },
        ),
    ]
