# Generated by Django 5.1.7 on 2025-09-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0045_pago_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago_servicio',
            name='monto_cotizado',
        ),
        migrations.RemoveField(
            model_name='pago_servicio',
            name='monto_pagado',
        ),
        migrations.RemoveField(
            model_name='pago_servicio',
            name='referencia_pago',
        ),
    ]
