# Generated by Django 5.1.7 on 2025-09-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0046_remove_pago_servicio_monto_cotizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_servicio_empresa',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se rechazó la solicitud', null=True),
        ),
        migrations.AddField(
            model_name='solicitud_servicio_empresa',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Motivo del rechazo de la solicitud', null=True),
        ),
        migrations.AddField(
            model_name='solicitud_servicio_usuario',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se rechazó la solicitud', null=True),
        ),
        migrations.AddField(
            model_name='solicitud_servicio_usuario',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Motivo del rechazo de la solicitud', null=True),
        ),
    ]
