# Generated by Django 5.1.7 on 2025-10-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0047_solicitud_servicio_empresa_fecha_rechazo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='latitud_empresa',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='longitud_empresa',
        ),
    ]
