# Generated by Django 5.1.7 on 2025-10-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0048_remove_empresa_latitud_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='avatar_chatbot_empresa',
            field=models.CharField(default='avatars/Cartoon Style Robot.jpg', help_text='Avatar para el chatbot de la empresa', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sector_empresa',
            field=models.CharField(blank=True, choices=[('tecnologia', 'Tecnología'), ('alimentos_bebidas', 'Alimentos y Bebidas'), ('moda_ropa', 'Moda y Ropa'), ('hogar', 'Hogar'), ('salud_belleza', 'Salud y Belleza'), ('deportes_ocio', 'Deportes y Ocio'), ('servicios', 'Servicios')], max_length=50, null=True),
        ),
    ]
