# Generated by Django 5.1.7 on 2025-10-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0049_empresa_avatar_chatbot_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_producto_empresa',
            name='generico',
            field=models.CharField(choices=[('s', 'Sí'), ('n', 'No')], default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='categoria_producto_usuario',
            name='generico',
            field=models.CharField(choices=[('s', 'Sí'), ('n', 'No')], default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='categoria_servicio_empresa',
            name='generico',
            field=models.CharField(choices=[('s', 'Sí'), ('n', 'No')], default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='categoria_servicio_usuario',
            name='generico',
            field=models.CharField(choices=[('s', 'Sí'), ('n', 'No')], default='n', max_length=1),
        ),
    ]
