# Generated by Django 5.1.7 on 2025-10-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0050_categoria_producto_empresa_generico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_usuario',
            name='cantidad_por_presentacion_producto_usuario',
            field=models.PositiveIntegerField(blank=True, help_text='Si aplica, cantidad de unidades por cada presentación (ej.: 6 por paquete).', null=True),
        ),
        migrations.AddField(
            model_name='producto_usuario',
            name='unidad_presentacion_producto_usuario',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('paquete', 'Paquete'), ('bulto', 'Bulto'), ('caja', 'Caja'), ('kg', 'Kilogramo'), ('l', 'Litro'), ('otro', 'Otro')], default='unidad', help_text='Formato de presentación del producto (unidades, paquetes, bultos, etc.)', max_length=20),
        ),
    ]
