# Generated by Django 5.1.7 on 2025-10-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0051_producto_usuario_cantidad_por_presentacion_producto_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_sucursal',
            name='cantidad_por_presentacion_producto_sucursal',
            field=models.PositiveIntegerField(blank=True, help_text='Si aplica, cantidad de unidades por presentación (ej.: 6 por paquete)', null=True),
        ),
        migrations.AddField(
            model_name='producto_sucursal',
            name='unidad_presentacion_producto_sucursal',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('paquete', 'Paquete'), ('bulto', 'Bulto'), ('caja', 'Caja'), ('kg', 'Kilogramo'), ('l', 'Litro'), ('otro', 'Otro')], default='unidad', help_text='Formato de presentación del producto en la sucursal', max_length=20),
        ),
    ]
