# Generated by Django 5.1.7 on 2025-10-19 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0052_producto_sucursal_cantidad_por_presentacion_producto_sucursal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_empresa_autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to='ecommerce_app.empresa')),
                ('id_usuario_autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to='ecommerce_app.usuario')),
                ('producto_sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='ecommerce_app.producto_sucursal')),
                ('producto_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='ecommerce_app.producto_usuario')),
                ('servicio_sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='ecommerce_app.servicio_sucursal')),
                ('servicio_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='ecommerce_app.servicio_usuario')),
            ],
            options={
                'db_table': 'comentarios',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['fecha_creacion'], name='comentarios_fecha_c_5f2e38_idx'), models.Index(fields=['producto_sucursal'], name='comentarios_product_7e3d4c_idx'), models.Index(fields=['producto_usuario'], name='comentarios_product_e8be19_idx'), models.Index(fields=['servicio_sucursal'], name='comentarios_servici_66aad9_idx'), models.Index(fields=['servicio_usuario'], name='comentarios_servici_6b90d7_idx'), models.Index(fields=['id_usuario_autor'], name='comentarios_id_usua_a5672c_idx'), models.Index(fields=['id_empresa_autor'], name='comentarios_id_empr_e8e386_idx')],
            },
        ),
    ]
