# Generated by Django 5.1.7 on 2025-10-19 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0053_comentario'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comentario',
            new_name='ecommerce_a_fecha_c_bf911c_idx',
            old_name='comentarios_fecha_c_5f2e38_idx',
        ),
        migrations.RenameIndex(
            model_name='comentario',
            new_name='ecommerce_a_product_09df1b_idx',
            old_name='comentarios_product_7e3d4c_idx',
        ),
        migrations.RenameIndex(
            model_name='comentario',
            new_name='ecommerce_a_product_0e442d_idx',
            old_name='comentarios_product_e8be19_idx',
        ),
        migrations.RenameIndex(
            model_name='comentario',
            new_name='ecommerce_a_servici_02acc3_idx',
            old_name='comentarios_servici_66aad9_idx',
        ),
        migrations.RenameIndex(
            model_name='comentario',
            new_name='ecommerce_a_servici_201ac4_idx',
            old_name='comentarios_servici_6b90d7_idx',
        ),
        migrations.RenameIndex(
            model_name='comentario',
            new_name='ecommerce_a_id_usua_019e38_idx',
            old_name='comentarios_id_usua_a5672c_idx',
        ),
        migrations.RenameIndex(
            model_name='comentario',
            new_name='ecommerce_a_id_empr_115e68_idx',
            old_name='comentarios_id_empr_e8e386_idx',
        ),
        migrations.AlterModelTable(
            name='comentario',
            table='ecommerce_app_comentario',
        ),
    ]
