# Generated by Django 5.1.7 on 2025-10-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0054_rename_comentarios_fecha_c_5f2e38_idx_ecommerce_a_fecha_c_bf911c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_sucursal',
            name='stock_reservado_sucursal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto_usuario',
            name='stock_reservado_usuario',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
