# Generated by Django 5.1.7 on 2025-10-27 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0055_producto_sucursal_stock_reservado_sucursal_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorito_empresa_sucursal',
            unique_together={('id_empresa_fk', 'id_producto_usuario_fk'), ('id_empresa_fk', 'id_servicio_usuario_fk')},
        ),
        migrations.AddField(
            model_name='favorito_empresa_sucursal',
            name='id_producto_sucursal_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_empresa', to='ecommerce_app.producto_sucursal'),
        ),
        migrations.AddField(
            model_name='favorito_empresa_sucursal',
            name='id_servicio_sucursal_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_empresa', to='ecommerce_app.servicio_sucursal'),
        ),
        migrations.AlterUniqueTogether(
            name='favorito_empresa_sucursal',
            unique_together={('id_empresa_fk', 'id_producto_sucursal_fk'), ('id_empresa_fk', 'id_producto_usuario_fk'), ('id_empresa_fk', 'id_servicio_sucursal_fk'), ('id_empresa_fk', 'id_servicio_usuario_fk')},
        ),
    ]
