# Generated by Django 5.1.7 on 2025-11-11 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0056_alter_favorito_empresa_sucursal_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('paypal', 'PayPal'), ('pago_movil', 'Pago Móvil')], help_text='Tipo de método de pago', max_length=15)),
                ('activo', models.BooleanField(default=True, help_text='Indica si este método de pago está disponible')),
                ('instrucciones', models.TextField(help_text='Instrucciones detalladas para realizar el pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre_beneficiario', models.CharField(blank=True, help_text='Nombre del titular de la cuenta', max_length=100, null=True)),
                ('numero_cuenta', models.CharField(blank=True, help_text='Número de cuenta, email o teléfono según el tipo', max_length=50, null=True)),
                ('banco', models.CharField(blank=True, help_text='Nombre del banco o entidad financiera', max_length=100, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, help_text='Tipo de cuenta (ej: Ahorros, Corriente, PayPal, etc.)', max_length=50, null=True)),
                ('identificador', models.CharField(blank=True, help_text='Cédula, RIF o identificador para pagos móviles', max_length=50, null=True)),
                ('datos_adicionales', models.JSONField(blank=True, help_text='Datos adicionales en formato JSON para integraciones futuras', null=True)),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa asociada a este método de pago (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago_empresa', to='ecommerce_app.empresa')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario asociado a este método de pago (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='ecommerce_app.usuario')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'metodos_pago',
                'ordering': ['tipo'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('empresa__isnull', True), ('usuario__isnull', False)), models.Q(('empresa__isnull', False), ('usuario__isnull', True)), _connector='OR'), name='solo_un_tipo_de_propietario')],
            },
        ),
    ]
