from django.urls import path
from . import views
from .views import *
urlpatterns = [
   
    path('iniciar_sesion/', iniciar_sesion, name='iniciar_sesion'),
    path('login_ajax/', login_ajax, name='login_ajax'),
    path('validate-email/', validate_email, name='validate_email'),
    path('prueba/', prueba, name='prueba'),
    path('debug_user_info/', debug_user_info, name='debug_user_info'),
    path('registrar_persona/',  registrar_persona, name='registrar_persona'),
    path('registrar_empresa/', registrar_empresa, name='registrar_empresa'),
    path('sucursal/', sucursalfuncion, name='sucursalfuncion'),
    path('editar_sucursal/', editar_sucursal, name='editar_sucursal'),
    path('eliminar_sucursal/', eliminar_sucursal, name='eliminar_sucursal'),
    path('eliminar_todas_sucursales/', eliminar_todas_sucursales, name='eliminar_todas_sucursales'),   
    path('categoria_producto/', views.categoria_producto_funcion, name='categoria_producto_funcion'),
    path('categ_producto_config/', categ_producto_config_funcion, name='categ_producto_config_funcion'),   
    path('producto/', producto_funcion, name='producto_funcion'),
    path('producto_config/', producto_config_funcion, name='producto_config_funcion'),
    path('editar_producto/', editar_producto, name='editar_producto'),
    path('eliminar_producto/', eliminar_producto, name='eliminar_producto'),
    path('eliminar_servicio/', eliminar_servicio, name='eliminar_servicio'),
    path('categoria_servicio/', categoria_servicio_funcion, name='categoria_servicio'),
    path('categ_servicio_config/', categ_servicio_config_funcion, name='categ_servicio_config_funcion'),
    path('servicio/', servicio_funcion, name='servicio_funcion'),
    path('servicio_config/', servicio_config_funcion, name='servicio_config_funcion'),
    path('eliminar_categoria_servicio/', eliminar_categoria_servicio_funcion, name='eliminar_categoria_servicio_funcion'),
    path('eliminar_categoria_producto/', eliminar_categoria_producto, name='eliminar_categoria_producto'),
    path('editar_categoria_producto/', editar_categoria_producto, name='editar_categoria_producto'),
    path('editar_categoria_servicio/', editar_categoria_servicio, name='editar_categoria_servicio'),
    path('editar_servicio/', editar_servicio, name='editar_servicio'),
    path('cerrar_sesion/', cerrar_sesion, name='cerrar_sesion'),
    path('logout_ajax/', logout_ajax, name='logout_ajax'),
    path('get-user-info/', get_user_info, name='get_user_info'),
    path('index/', index, name='index'),
    path('api/categorias_producto/', views.api_categorias_producto, name='api_categorias_producto'),
    path('api/categorias_servicio/', views.api_categorias_servicio, name='api_categorias_servicio'),
    path('api/filtrar_categorias_producto/', views.api_filtrar_categorias_producto, name='api_filtrar_categorias_producto'),
    path('api/filtrar_categorias_servicio/', views.api_filtrar_categorias_servicio, name='api_filtrar_categorias_servicio'),
    path('api/filtrar_servicios/', views.api_filtrar_servicios, name='api_filtrar_servicios'),
    path('api/filtrar_productos/', views.api_filtrar_productos, name='api_filtrar_productos'),
    path('api/obtener_imagenes_producto/', views.api_obtener_imagenes_producto, name='api_obtener_imagenes_producto'),
    path('api/obtener_imagenes_servicio/', views.api_obtener_imagenes_servicio, name='api_obtener_imagenes_servicio'),
    path('api/eliminar_imagen_producto/', views.api_eliminar_imagen_producto, name='api_eliminar_imagen_producto'),
    path('api/eliminar_imagen_servicio/', views.api_eliminar_imagen_servicio, name='api_eliminar_imagen_servicio'),
    path('perfil_empresa/', views.perfil_empresa, name='perfil_empresa'),
    path('cambiar_logo_empresa/', views.cambiar_logo_empresa, name='cambiar_logo_empresa'),
    path('perfil_usuario/', views.perfil_usuario, name='perfil_usuario'),
    path('cambiar_foto_usuario/', views.cambiar_foto_usuario, name='cambiar_foto_usuario'),

    # API para productos y servicios no asociados a una sucursal
    path('api/productos_servicios_disponibles/', views.api_productos_servicios_disponibles, name='api_productos_servicios_disponibles'),
    # API para guardar producto o servicio en una sucursal
    path('api/guardar_producto_servicio_sucursal/', views.guardar_producto_servicio_sucursal, name='guardar_producto_servicio_sucursal'),
    path('busquedad/', views.busquedad, name='busquedad'),
    path('localizacion/', views.localizacion, name='localizacion'),
    path('carrito/', views.carrito, name='carrito'),
    path('vista_items/', views.vista_items, name='vista_items'),
    path('perfil_sucursales_asociadas/', views.perfil_sucursales_asociadas, name='perfil_sucursales_asociadas'),
    path('perfil_productos/', views.perfil_productos, name='perfil_productos'),
    path('perfil_servicios/', views.perfil_servicios, name='perfil_servicios'),
    path('detalle_carrito/', views.detalle_carrito, name='detalle_carrito'),
    path('agregar_al_carrito/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('eliminar_del_carrito/', views.eliminar_del_carrito, name='eliminar_del_carrito'),
    path('actualizar_cantidad_carrito/', views.actualizar_cantidad_carrito, name='actualizar_cantidad_carrito'),
    path('pedido/', views.pedido, name='pedido'),
    path('procesar_pedido/', views.procesar_pedido, name='procesar_pedido'),
    path('confirmacion_pedido/', views.confirmacion_pedido, name='confirmacion_pedido'),
    path('mis_pedidos/', views.mis_pedidos, name='mis_pedidos'),
    path('mis_ventas/', views.mis_ventas, name='mis_ventas'),
    path('confirmar_venta/', views.confirmar_venta, name='confirmar_venta'),




]